from ._codec import Metadata, ScalarMetadata

def version() -> tuple[str, str]: ...
def abi_layout() -> dict[str, tuple[int, ...] | tuple[int, tuple[int, ...]]]: ...

class FileHandle:
    def __init__(self, path: str, readonly: bool) -> None: ...
    def close(self) -> None: ...
    def read(self, name: str) -> tuple[int, int, bytes, Metadata, str]: ...
    def write(self, name: str, year: int, month: int, payload: bytes) -> None: ...
    def read_scalar(self, name: str) -> tuple[bytes, ScalarMetadata, str]: ...
    def write_scalar(self, name: str, payload: bytes) -> None: ...
