# SPDX-License-Identifier: MIT
"""TimeSeriesEconPy: a time-series language for macroeconomics.

Ported from `TimeSeriesEcon.jl`_ (Bank of Canada).

.. _TimeSeriesEcon.jl: https://github.com/bankofcanada/TimeSeriesEcon.jl
"""

from tsecon._bdaily import bdvalues, cleanedvalues
from tsecon._math import (
    apct,
    diff,
    lag,
    lag_inplace,
    lead,
    lead_inplace,
    moving,
    moving_average,
    moving_sum,
    pct,
    shift,
    shift_inplace,
    undiff,
    undiff_inplace,
    undiff_is_cython,
    ytypct,
)
from tsecon._mirror import MIRRORS_JULIA_SHA
from tsecon._options import (
    clear_holidays_map,
    get_holidays_map,
    getoption,
    option_scope,
    set_holidays_map,
    setoption,
)
from tsecon._stats import (
    cor,
    cov,
    mean,
    median,
    quantile,
    stats_is_cython,
    std,
    stdm,
    var,
    varm,
)
from tsecon.fconvert import (
    extend_series,
    fconvert,
    fconvert_is_cython,
    fconvert_mit,
    fconvert_parts,
    fconvert_range,
    fconvert_tseries,
    strip_tseries,
    strip_tseries_inplace,
    trim_series,
)
from tsecon.frequencies import (
    BDaily,
    CalendarFrequency,
    Daily,
    Frequency,
    HalfYearly,
    Monthly,
    Quarterly,
    Unit,
    Weekly,
    Yearly,
    YPFrequency,
    endperiod,
    is_bdaily,
    is_daily,
    is_halfyearly,
    is_monthly,
    is_quarterly,
    is_weekly,
    is_yearly,
    ppy,
    prettyprint_frequency,
    sanitize_frequency,
)
from tsecon.indexing import lookup, lookup_is_cython

# interop must import after TSeries/MVTSeries/Workspace are loaded — it
# attaches `to_pandas` / `to_polars` method delegates onto those classes.
from tsecon.interop import from_pandas, from_polars, to_pandas, to_polars
from tsecon.mit import (
    MIT,
    Duration,
    bdaily,
    daily,
    frequency_of,
    mit2yp,
    mit_to_date,
    mm,
    period,
    qq,
    weekly,
    weekly_from_iso,
    year,
    yy,
)
from tsecon.mitrange import MITRange, mitrange, rangeof_span
from tsecon.mvtseries import MVTSeries, hcat, rename_columns_inplace, vcat
from tsecon.plotting import (
    BackendNotAvailableError,
    available_backends,
    plot,
    resolve_backend,
)
from tsecon.recursive import rec, rec_linear, rec_linear_is_cython
from tsecon.tseries import TSeries, typenan
from tsecon.workspace import Workspace

__version__ = "0.0.1.dev0"

__all__ = [
    "MIRRORS_JULIA_SHA",
    "MIT",
    "BDaily",
    "BackendNotAvailableError",
    "CalendarFrequency",
    "Daily",
    "Duration",
    "Frequency",
    "HalfYearly",
    "MITRange",
    "MVTSeries",
    "Monthly",
    "Quarterly",
    "TSeries",
    "Unit",
    "Weekly",
    "Workspace",
    "YPFrequency",
    "Yearly",
    "__version__",
    "apct",
    "available_backends",
    "bdaily",
    "bdvalues",
    "cleanedvalues",
    "clear_holidays_map",
    "cor",
    "cov",
    "daily",
    "diff",
    "endperiod",
    "extend_series",
    "fconvert",
    "fconvert_is_cython",
    "fconvert_mit",
    "fconvert_parts",
    "fconvert_range",
    "fconvert_tseries",
    "frequency_of",
    "from_pandas",
    "from_polars",
    "get_holidays_map",
    "getoption",
    "hcat",
    "is_bdaily",
    "is_daily",
    "is_halfyearly",
    "is_monthly",
    "is_quarterly",
    "is_weekly",
    "is_yearly",
    "lag",
    "lag_inplace",
    "lead",
    "lead_inplace",
    "lookup",
    "lookup_is_cython",
    "mean",
    "median",
    "mit2yp",
    "mit_to_date",
    "mitrange",
    "mm",
    "moving",
    "moving_average",
    "moving_sum",
    "option_scope",
    "pct",
    "period",
    "plot",
    "ppy",
    "prettyprint_frequency",
    "qq",
    "quantile",
    "rangeof_span",
    "rec",
    "rec_linear",
    "rec_linear_is_cython",
    "rename_columns_inplace",
    "resolve_backend",
    "sanitize_frequency",
    "set_holidays_map",
    "setoption",
    "shift",
    "shift_inplace",
    "stats_is_cython",
    "std",
    "stdm",
    "strip_tseries",
    "strip_tseries_inplace",
    "to_pandas",
    "to_polars",
    "trim_series",
    "typenan",
    "undiff",
    "undiff_inplace",
    "undiff_is_cython",
    "var",
    "varm",
    "vcat",
    "weekly",
    "weekly_from_iso",
    "year",
    "ytypct",
    "yy",
]
