# SPDX-License-Identifier: MIT
"""TimeSeriesEconPy: a time-series language for macroeconomics.

Ported from `TimeSeriesEcon.jl`_ (Bank of Canada).

.. _TimeSeriesEcon.jl: https://github.com/bankofcanada/TimeSeriesEcon.jl
"""

from tsecon._math import (
    apct,
    diff,
    lag,
    lag_inplace,
    lead,
    lead_inplace,
    moving,
    moving_average,
    moving_sum,
    pct,
    shift,
    shift_inplace,
    undiff,
    undiff_inplace,
    ytypct,
)
from tsecon._mirror import MIRRORS_JULIA_SHA
from tsecon.frequencies import (
    BDaily,
    CalendarFrequency,
    Daily,
    Frequency,
    HalfYearly,
    Monthly,
    Quarterly,
    Unit,
    Weekly,
    Yearly,
    YPFrequency,
    endperiod,
    is_bdaily,
    is_daily,
    is_halfyearly,
    is_monthly,
    is_quarterly,
    is_weekly,
    is_yearly,
    ppy,
    prettyprint_frequency,
    sanitize_frequency,
)
from tsecon.mit import (
    MIT,
    Duration,
    bdaily,
    daily,
    frequency_of,
    mit2yp,
    mit_to_date,
    mm,
    period,
    qq,
    weekly,
    weekly_from_iso,
    year,
    yy,
)
from tsecon.mitrange import MITRange, mitrange, rangeof_span
from tsecon.tseries import TSeries, typenan
from tsecon.workspace import Workspace

__version__ = "0.0.1.dev0"

__all__ = [
    "MIRRORS_JULIA_SHA",
    "MIT",
    "BDaily",
    "CalendarFrequency",
    "Daily",
    "Duration",
    "Frequency",
    "HalfYearly",
    "MITRange",
    "Monthly",
    "Quarterly",
    "TSeries",
    "Unit",
    "Weekly",
    "Workspace",
    "YPFrequency",
    "Yearly",
    "__version__",
    "apct",
    "bdaily",
    "daily",
    "diff",
    "endperiod",
    "frequency_of",
    "is_bdaily",
    "is_daily",
    "is_halfyearly",
    "is_monthly",
    "is_quarterly",
    "is_weekly",
    "is_yearly",
    "lag",
    "lag_inplace",
    "lead",
    "lead_inplace",
    "mit2yp",
    "mit_to_date",
    "mitrange",
    "mm",
    "moving",
    "moving_average",
    "moving_sum",
    "pct",
    "period",
    "ppy",
    "prettyprint_frequency",
    "qq",
    "rangeof_span",
    "sanitize_frequency",
    "shift",
    "shift_inplace",
    "typenan",
    "undiff",
    "undiff_inplace",
    "weekly",
    "weekly_from_iso",
    "year",
    "ytypct",
    "yy",
]
