# SPDX-License-Identifier: MIT
# Capture a Julia-side `d11` reference for the M2.6 fidelity test.
#
# The Python wrapper at `src/tsecon/x13/` and the Julia upstream at
# `TimeSeriesEcon.jl/src/x13/` are intended to produce identical seasonal-
# adjustment output when run against the same X-13ARIMA-SEATS binary.
# This script:
#
# 1. Forces Julia to use the same `x13as.exe` the Python tests use, via
#    `setoption(:x13path, ...)`. That side-steps the X13as_jll version
#    drift (Yggdrasil ships b60; we vendor b62).
# 2. Builds the same deterministic Quarterly TSeries the Python test does
#    (trend + sinusoidal seasonal, no random component).
# 3. Runs `X13.run(spec, load = :d11)` and writes `d11.values` to
#    `tests/x13/fixtures/d11_julia_reference.csv` (one float per line,
#    full 17-digit `%.17g` precision so the Python side can lock 1e-10).
#
# Run from the project root::
#
#     julia --project=c:/Users/.../TimeSeriesEcon.jl tests/x13/fixtures/capture_julia_d11.jl
#
# Re-running the script overwrites the fixture; commit the result.

using TimeSeriesEcon
using TimeSeriesEcon: X13
using Printf

# Resolve the bundled binary path from the project tree.
const REPO_ROOT = normpath(joinpath(@__DIR__, "..", "..", ".."))
const BINARY = Sys.iswindows() ?
    joinpath(REPO_ROOT, "src", "tsecon", "x13", "_binary", "x13as.exe") :
    joinpath(REPO_ROOT, "src", "tsecon", "x13", "_binary", "x13as")

isfile(BINARY) || error("X-13 binary not found at $(BINARY). Run scripts/fetch_x13as_local.py first.")
TimeSeriesEcon.setoption(:x13path, BINARY)

# --- Build the same Quarterly fixture the Python test uses -----------
# trend(i) = 100 + 0.5*i
# seasonal(i) = 5*sin(2*pi*i/4)
# series[i] = trend(i) + seasonal(i)
# i in 0:N-1, N=100, starts 2000Q1.
const N = 100
trend = [100.0 + 0.5*i for i in 0:N-1]
seasonal = [5.0 * sin(2*pi*i/4) for i in 0:N-1]
values = trend .+ seasonal

ts = TSeries(2000Q1, values)

# --- Run X-13 with x11(save = :d11) ----------------------------------
spec = X13.newspec(ts)
X13.x11!(spec; save = :d11)
result = X13.run(spec; verbose = false, load = :d11)

d11 = result.series.d11
println("Captured d11: length=", length(d11.values), " freq=", frequencyof(d11))

# --- Write fixture ----------------------------------------------------
fixture_path = joinpath(@__DIR__, "d11_julia_reference.csv")
open(fixture_path, "w") do io
    println(io, "# Julia-side d11 reference for the M2.6 fidelity test.")
    println(io, "# Source binary: src/tsecon/x13/_binary/x13as[.exe] (X-13ARIMA-SEATS v1.1 b62).")
    println(io, "# Series: 100 quarters starting 2000Q1, trend + sinusoidal seasonal.")
    println(io, "# One float per line, %.17g precision. Length should match the Python side.")
    println(io, "# Generated by tests/x13/fixtures/capture_julia_d11.jl.")
    for v in d11.values
        @printf(io, "%.17g\n", v)
    end
end
println("Wrote ", fixture_path)
