# SPDX-License-Identifier: MIT
"""Diff the pinned TimeSeriesEcon.jl SHA against upstream HEAD.

Run by the ``upstream-sync`` GitHub Actions workflow. Opens or updates a
tracking issue when there are unported upstream commits in ``src/``.

Standalone-runnable for local testing::

    uv run python scripts/check_mirror.py

Requires the ``gh`` CLI on ``PATH`` when running locally; in CI it uses the
default ``GITHUB_TOKEN``.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# Make ``src/`` importable so we can read the pinned SHA without installing
# the package (CI does install, but local runs may not).
sys.path.insert(0, str(REPO_ROOT / "src"))
from tsecon._mirror import MIRRORS_JULIA_REPO, MIRRORS_JULIA_SHA  # noqa: E402

TRACKING_LABEL = "upstream-sync"
TRACKING_TITLE_PREFIX = "Upstream sync:"


def run(cmd: list[str]) -> subprocess.CompletedProcess[str]:
    """Run a shell command and return the completed process."""
    print(f"$ {' '.join(cmd)}", flush=True)
    return subprocess.run(cmd, capture_output=True, text=True, check=True)


def clone_upstream(workdir: Path) -> Path:
    """Shallow-clone the upstream Julia repo into ``workdir``."""
    repo_dir = workdir / "TimeSeriesEcon.jl"
    run(
        [
            "git",
            "clone",
            "--depth",
            "200",
            f"https://github.com/{MIRRORS_JULIA_REPO}.git",
            str(repo_dir),
        ]
    )
    return repo_dir


def diff_against_pinned(repo_dir: Path, pinned_sha: str) -> tuple[str, list[str]]:
    """Return (upstream HEAD sha, list of changed files in ``src/``)."""
    head = run(["git", "-C", str(repo_dir), "rev-parse", "HEAD"]).stdout.strip()
    if head == pinned_sha:
        return head, []
    diff = run(
        [
            "git",
            "-C",
            str(repo_dir),
            "diff",
            "--name-only",
            f"{pinned_sha}..HEAD",
            "--",
            "src",
        ]
    )
    files = [line.strip() for line in diff.stdout.splitlines() if line.strip()]
    return head, files


def find_existing_issue(gh_repo: str) -> int | None:
    """Return the issue number of the existing tracking issue, if any."""
    result = run(
        [
            "gh",
            "issue",
            "list",
            "--repo",
            gh_repo,
            "--label",
            TRACKING_LABEL,
            "--state",
            "open",
            "--json",
            "number,title",
            "--limit",
            "5",
        ]
    )
    issues = json.loads(result.stdout or "[]")
    for issue in issues:
        if issue["title"].startswith(TRACKING_TITLE_PREFIX):
            return int(issue["number"])
    return None


def upsert_tracking_issue(
    gh_repo: str, pinned_sha: str, head_sha: str, changed_files: list[str]
) -> None:
    """Open or update the tracking issue with the latest diff."""
    title = f"{TRACKING_TITLE_PREFIX} {len(changed_files)} changed file(s) since pinned SHA"
    body_lines = [
        "## Upstream changes detected",
        "",
        f"**Pinned SHA:** `{pinned_sha}`",
        f"**Upstream HEAD:** `{head_sha}`",
        f"**Compare:** https://github.com/{MIRRORS_JULIA_REPO}/compare/{pinned_sha}...{head_sha}",
        "",
        "### Changed files in `src/`",
        "",
    ]
    body_lines.extend(f"- `{f}`" for f in changed_files)
    body_lines.extend(
        [
            "",
            "---",
            "*Auto-generated by `.github/workflows/upstream-sync.yml`. Update"
            " `MIRRORS_JULIA_SHA` in `src/tsecon/_mirror.py` once these are ported.*",
        ]
    )
    body = "\n".join(body_lines)

    existing = find_existing_issue(gh_repo)
    if existing is None:
        run(
            [
                "gh",
                "issue",
                "create",
                "--repo",
                gh_repo,
                "--title",
                title,
                "--body",
                body,
                "--label",
                TRACKING_LABEL,
            ]
        )
    else:
        run(
            [
                "gh",
                "issue",
                "edit",
                str(existing),
                "--repo",
                gh_repo,
                "--title",
                title,
                "--body",
                body,
            ]
        )


def main() -> int:
    """Entry point."""
    gh_repo = os.environ.get("GH_REPO", "Nic2020/TimeSeriesEconPy")

    with tempfile.TemporaryDirectory() as tmp:
        workdir = Path(tmp)
        repo_dir = clone_upstream(workdir)
        head, files = diff_against_pinned(repo_dir, MIRRORS_JULIA_SHA)

    if not files:
        print(f"In sync with upstream HEAD {head}; no action needed.")
        return 0

    print(f"Upstream HEAD={head}; {len(files)} changed file(s) in src/.")
    for f in files:
        print(f"  {f}")

    if os.environ.get("GH_TOKEN"):
        upsert_tracking_issue(gh_repo, MIRRORS_JULIA_SHA, head, files)
    else:
        print("(no GH_TOKEN; skipping issue creation)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
